CREATE TABLE IF NOT EXISTS SPACESHIPS(
    ID INT PRIMARY KEY,
    SPACESHIPS_NAMES VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS MODULES(
    ID INT PRIMARY KEY,
    MODULES_NAMES VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS EQUIPMENT(
    ID INT PRIMARY KEY,
    EQUIPMENT_NAMES VARCHAR(80) NOT NULL,
    FEATURE VARCHAR(80) NOT NULL,
    MODULES INT REFERENCES MODULES(ID),
    SPACESHIPS INT REFERENCES SPACESHIPS(ID)
);
CREATE TABLE IF NOT EXISTS TITLES(
    ID PRIMARY KEY,
    TITLE VARCHAR(40) NOT NULL,
    EQUIPMENT INT REFERENCES EQUIPMENT(ID)
);