#!/bin/bash

#1
mkdir lab0
mkdir -p ekans8/{claydol,grumpig,torterra}
touch armaldo3
echo "satk=7 sdef=8 spd=5" > armaldo3
touch bayleef6
touch pikachu1
echo "Ходы Body \nSlam Counter Cover Defence Curl Double-Edge Dynamicpuch Focus Punch \nHelping Hand Iron Tail Knock Off Magnet Rise Mega Kick Mega Punch Mud-Slap Rollout Seismic Toss Shock Wave Signal Beam Sleep Talk Shore \nSwift Thunderpunch Uproar" > pikachu1

mkdir -p ekans8/{claydol,grumpig,torterra}
touch gallade2/{purrloin,shinx}
echo "Способности Scratch Growl Assist \nSad-Attack Fury Swipes Pursuit Torment Fake Out Hone Claws Assurance \nSlash Captivate Night Slash Satch Nasty Plot Sucker \nPunch" > purrloin
echo "Развитые способности Guts" > shinx
mkdir scyther

mkdir -p nidorino3/{shellder,omanyte}
touch nidorino3/{leafeon,azurill}
echo "Споссобноти \nSand-Attack Razor Leaf Quick Attack Grasswhistle Magical Leaf Giga \nDrain Swords Dance Synthesis Suny Day Last Resort Leaaf \nBlade" > leafeon
echo "weigth=4.4 height=8.0 def=4"c > azurill

echo "________________________________________________________"

#2
chmod a=rw- armaldo3
chmod 444 bayleef6
chmod 577 ekans8
chmod a=rwx  ekans8/claydol
chmod 307 ekans8/grumpig
chmod 355 ekans8/torterra
chmod u= -wx go=--x gallade2
chmod 622 gallade2/purrloin
chmod 736 gallade2/scyther
chmod 006 gallade2/shinx
chmod 307 nidorino3
chmod u= -wx go=--x nidorino3/shellder
chmod 046 nidorino3/leafeon
chmod 404 nidorino3/azurill
chmod 571 nidorino3/omanyte
chmod a=r--

ls -lR

echo "________________________________________________________"

#3
ln -s armaldo3 gallade2/purrloinarmaldo
cat nidorino3/leafeon nidorino3/azurill > bayleef6_63
ln pikachu1 gallade2/purrloinpikachu
cp bayleef6 nidorino3/azurillbayleef
cp -r gallade2/ ekans8/torterra
ln -s ekans8 Copy_31
cp pikachu1 nidorino3/omanyte 

echo "________________________________________________________"

#4

