CREATE TABLE IF NOT EXISTS SPACESHIPS(
    ID INT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS PLACES(
    ID INT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
);
CREATE TABLE IF NOT EXISTS GONDOLAS(
    ID INT UNIQUE REFERENCES EQUIPMENT(ID),
    NAME VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACTIONS(
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS EQUIPMENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    FUNCTION_NAME VARCHAR(100) NOT NULL,
    PLACE_ID INT REFERENCES PLACES(ID) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS SPACESHIPS_TO_EQUIPMENT(
    SPACESHIPS_ID INT REFERENCES SPACESHIPS(ID) ON UPDATE CASCADE,
    EQUIPMENT_ID INT REFERENCES EQUIPMENT(ID) ON UPDATE CASCADE,
    CONSTRAINT SPACESHIP_EQUIPMENT_ID FOREIGN KEY(SPACESHIP_ID, EQUIPMENT_ID)
);

CREATE TABLE IF NOT EXIST EQUIPMENT_ACTIONS(
    EQUIPMENT_ID INT REFERENCES EQUIPMENT(ID) ON UPDATE CASCADE,
    ACTION_ID INT REFERENCES ACTIONS(ID) ON UPDATE CASCADE,
    CONSTRAINT EQUIPMENT_ACTIONS_ID FOREIGN KEY(EQUIPMENT_ID, ACTION_ID)
);
